name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0

dependency_overrides:
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
