name: netflix_clone
description: This project is a clone of the Netflix app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  chewie: ^1.10.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  formz: ^0.8.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^14.8.0
  hydrated_bloc: ^10.0.0
  injectable: ^2.5.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.3
  youtube_player_flutter: ^9.1.1

dependency_overrides:
  analyzer: ^6.3.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  isar_generator: ^3.1.0+1
  json_serializable: ^6.9.0
  mockito: ^5.4.5
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.9
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/svgs/
    - assets/lotties/
    - assets/mock/

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf

        - asset: assets/fonts/NotoSansThai-Medium.ttf
          weight: 600

        - asset: assets/fonts/NotoSansThai-Black.ttf
          weight: 700

        - asset: assets/fonts/NotoSansThai-Bold.ttf
          weight: 900
